### ISSUE TITLE
Getting error while installing Jupyter Dashboard

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyter/dashboards#299]
Hi Team,

While installing Jupyter Dashboard using the command: conda install -c conda-forge jupyter_dashboards=0.7.0 -v it throws error during linking. 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /app/install/jupyter/anaconda3  (writable)
    default environment : /app/install/jupyter/anaconda3
       envs directories : /app/install/jupyter/anaconda3/envs
                          /root/.conda/envs
          package cache : /app/install/jupyter/anaconda3/pkgs
                          /root/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.13.0 CPython/3.5.2 Linux/3.10.0-123.20.1.el7.x86_64 CentOS Linux/7.0.1406 glibc/2.17
                UID:GID : 0:0

`$ /app/install/jupyter/anaconda3/bin/conda install -c conda-forge jupyter_dashboards=0.7.0 -v`

    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 500, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/app/install/jupyter/anaconda3/bin/.jupyter_dashboards-post-link.sh']' returned non-zero exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 516, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package conda-forge::jupyter_dashboards-0.7.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: /app/install/jupyter/anaconda3/bin/.jupyter_dashboards-post-link.sh
    ==> script messages <==
    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/bin/jupyter-dashboards", line 4, in <module>
        import jupyter_dashboards.extensionapp
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 8, in <module>
        from notebook.nbextensions import (InstallNBExtensionApp, EnableNBExtensionApp,
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
        from .nbextensions import install_nbextension
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 32, in <module>
        from traitlets.config.manager import BaseJSONConfigManager
    ImportError: No module named 'traitlets.config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package conda-forge::jupyter_dashboards-0.7.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: /app/install/jupyter/anaconda3/bin/.jupyter_dashboards-post-link.sh
    ==> script messages <==
    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/bin/jupyter-dashboards", line 4, in <module>
        import jupyter_dashboards.extensionapp
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 8, in <module>
        from notebook.nbextensions import (InstallNBExtensionApp, EnableNBExtensionApp,
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
        from .nbextensions import install_nbextension
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 32, in <module>
        from traitlets.config.manager import BaseJSONConfigManager
    ImportError: No module named 'traitlets.config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 363, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package conda-forge::jupyter_dashboards-0.7.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: /app/install/jupyter/anaconda3/bin/.jupyter_dashboards-post-link.sh
    ==> script messages <==
    Traceback (most recent call last):
      File "/app/install/jupyter/anaconda3/bin/jupyter-dashboards", line 4, in <module>
        import jupyter_dashboards.extensionapp
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 8, in <module>
        from notebook.nbextensions import (InstallNBExtensionApp, EnableNBExtensionApp,
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
        from .nbextensions import install_nbextension
      File "/app/install/jupyter/anaconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 32, in <module>
        from traitlets.config.manager import BaseJSONConfigManager
    ImportError: No module named 'traitlets.config'
*************************************************************************************************************

Just to let you know that Trailets is also installed.

Can you please help me on this,.

**Comment by parente** [comment]
Can you please run conda list and post the version of notebook you have installed?

**Comment by sudipto84goswami** [comment]
Hi Peter,

Thanks for reviewing my question.

I am providing some details of my environment:

1. Conda Version: 4.3.22
2. Conda List is attached herewith.

Can you please let us know further.
[conda_list_output.txt](https://github.com/jupyter/dashboards/files/1113989/conda_list_output.txt)

**Comment by parente** [comment]
From your conda list:

```
traitlets                 4.3.2                     <pip>
traitlets                 4.2.1                    py35_0 
```

It's possible that the traitlets package is not installed properly when it was first installed by conda and then overwritten by pip. You might try:

```
pip uninstall traitlets
conda remove traitlets
conda install traitlets
```

**Comment by parente** [comment]
@sudipto84goswami I'm going to close this issue because it's been inactive for over a month now. If you tried the uninstall / reinstall steps with traitlets above and are still stuck, feel free to reopen and post your current status.
