### ISSUE TITLE
dashboard installed as user and virtalenvs

### ISSUE THREAD

**Issue by deisi** [jupyter/dashboards#300]
Hey, I'm struggling installing jupyter_dashboard.

I have installed jupyter as local user with:

 ``` 
pip3 instll --user jupyter
pip3 install --user jupyter_dashboard
...
```

When I run 
``` bash
jupyter dashboards quick-setup --sys-prefix
```
I get:
```
Installing /home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/nbextension -> jupyter_dashboards
Traceback (most recent call last):
  File "/home/malte/.local/bin/jupyter-dashboards", line 11, in <module>
    sys.exit(main())
  File "/home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 203, in main
    ExtensionApp.launch_instance()
  File "/home/malte/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 199, in start
    super(ExtensionApp, self).start()
  File "/home/malte/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 305, in start
    return self.subapp.start()
  File "/home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 122, in start
    install.start()
  File "/home/malte/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/home/malte/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 657, in install_extensions
    **kwargs
  File "/home/malte/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/malte/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/malte/.local/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'
```
`/usr/share/jupyte` seems to be the wrong folder anyways because I want to install as user and not systemwide.
So i run:

```
jupyter dashboards quick-setup --user malte
```

I get 
```
Traceback (most recent call last):
  File "/home/malte/.local/bin/jupyter-dashboards", line 11, in <module>
    sys.exit(main())
  File "/home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 203, in main
    ExtensionApp.launch_instance()
  File "/home/malte/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 199, in start
    super(ExtensionApp, self).start()
  File "/home/malte/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 305, in start
    return self.subapp.start()
  File "/home/malte/.local/lib/python3.5/site-packages/jupyter_dashboards/extensionapp.py", line 122, in start
    install.start()
  File "/home/malte/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/home/malte/.local/lib/python3.5/site-packages/notebook/nbextensions.py", line 639, in install_extensions
    raise ValueError("Only one nbextension allowed at a time. "
ValueError: Only one nbextension allowed at a time. Call multiple times to install multiple extensions.
```

If I understand this correctly jupyter tries to install dashboard in:
```
ls ~/.local/lib/python3.5/site-packages/jupyter_dashboards/nbextension/
```
ans this shows a single folder `notebook`. So I don't know what this means? Should I delete the `notebook` folder and try again? What is the message about?

**Comment by parente** [comment]
The `--sys-prefix` flag for `quick-setup` installs and enables the extension in the virtual environment path. If you want to enable for the local user, use:

```
jupyter dashboards quick-setup --user
```

However, now that you've installed it once with `--sys-prefix` you probably need to first uninstall / disable the extension. Altogether, try running:

```
# disable and uninstall from the virtual env config folder
jupyter dashboards quick-remove --sys-prefix
# now install and enable in the current user home config folder
jupyter dashboards quick-setup --user
```

**Comment by deisi** [comment]
Okay I will test ASAP. Thx

**Comment by quipa** [comment]
@parente I had the same issue and tried running `jupyter dashboards quick-setup --user` as you suggested and seems to have worked! After running the command this is shown at the end:
```
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable jupyter_dashboards --user --py
    
Enabling notebook extension jupyter_dashboards/notebook/main...
      - Validating: OK
```
